[paths]
output_dir_base = "results"
sources_dir = "sources"
account_jsons_dir = "videos_jsons"
cookies_dir = "cookies"

[default]
language = "en"
account = "dbnz"
source_file_path = ""
subs_file_path = ""
timecodes = []
clips_json_path = ""

[accounts.dbnz]
json = "videos_jsons/dbnz.json"
accountname = "En Account"

[accounts.scm]
json = "videos_jsons/scm.json"
accountname = "Ru Account"
